version: '3.8'

volumes:
  tomcat-conf:

services:
  tomcat:
    container_name: tomcat
    image: tomcat:9.0.58-jre11-openjdk-bullseye
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./tomcat-webapps:/usr/local/tomcat/webapps:cached
      - tomcat-conf:/usr/local/tomcat/conf
